membersrvc:
 image: hyperledger/fabric-membersrvc
 ports:
  - "7054:7054"
 command: membersrvc
vp0:
 image: hyperledger/fabric-peer
 ports:
  - "7050:7050"
  - "7051:7051"
  - "7053:7053"
 environment:
  - CORE_PEER_ADDRESSAUTODETECT=false
  - CORE_PEER_ADDRESS=192.168.99.100:7051
  - CORE_VM_ENDPOINT=unix:///var/run/docker.sock
  - CORE_LOGGING_LEVEL=DEBUG
  - CORE_PEER_ID=vp0
  - CORE_SECURITY_ENABLED=true
  - CORE_SECURITY_ENROLLID=test_vp0
  - CORE_SECURITY_ENROLLSECRET=MwYpmSRjupbT
  - CORE_PEER_PKI_ECA_PADDR=membersrvc:7054
  - CORE_PEER_PKI_TCA_PADDR=membersrvc:7054
  - CORE_PEER_PKI_TLSCA_PADDR=membersrvc:7054
  - CORE_PEER_VALIDATOR_CONSENSUS_PLUGIN=pbft
  - CORE_PBFT_GENERAL_MODE=batch
  - CORE_PBFT_GENERAL_BATCHSIZE=1000
  - CORE_PBFT_GENERAL_TIMEOUT_REQUEST=4s
 volumes:
  - /var/run/docker.sock:/var/run/docker.sock
 links:
  - membersrvc
 command: sh -c "sleep 5; peer node start"
